[package]
name = "library"
version = "0.1.0"
edition = "2024"

[dependencies]
ffmpeg-next = "7.0"
libc = "0.2.177"
tokio = { version = "1.48.0", features = ["full"] }
anyhow = "1.0.100"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
once_cell = "1"
reqwest = { version = "0.11", features = ["json"] }

# [lib]
# crate-type = ["cdylib"]