[package]
name = "client_video"
version = "0.1.0"
edition = "2021"

[dependencies]
ffmpeg-next = { version = "7.1", features = ["static"] }
libc = "0.2.177"
tokio = { version = "1.48.0", features = ["full"] }
anyhow = "1.0.100"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
once_cell = "1"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }

[lib]
crate-type = ["cdylib"]
name = "client_video"