local: true
environment: NonProduction

sources_config:
  ids: [1]
  default:
    inf_frame: 2
    conf_threshold: 0.50
    nms_iou_threshold: 0.5
  custom:
    1:
      conf_threshold: 0.75

kafka_config:
  brokers: localhost:9092
  topic_bboxes: bboxes
  topic_embedding: embedding

triton_config:
  url: http://localhost:8001
  models_dir: /mnt/disk_e/Programming/real-time-object-detection/client-triton/triton_models

inference_config:
  task: ObjectDetection
  models:
    YOLO:
      name: yolov9-e
      precision: FP16
      input_name: images
      input_shape: [3, 640, 640]
      output_name: output
      output_shape: [84, 8400]
      batch_max_size: 16
      batch_max_queue_delay: 2500
      batch_preferred_sizes: [2,4,6,8]

    DINO:
      name: dinov3-vitb16
      precision: FP16
      input_name: images
      input_shape: [3, 224, 224]
      output_name: output
      output_shape: [768]
      batch_max_size: 16
      batch_max_queue_delay: 1000
      batch_preferred_sizes: [4, 8, 16]